# SPDX-License-Identifier: AGPL-3.0-or-later

homepage: "https://github.com/hyperpolymath/vext"
language: rust
primary_contact: "jonathan.jewell@open.ac.uk"
auto_ccs:
  - "jonathan.jewell@open.ac.uk"
sanitizers:
  - address
  - undefined
  - memory
